/* 
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

List<int> numbers = new List<int>();

numbers.Add(1);
numbers.Add(2);

while (numbers.Last() < 4000000)
{
    int last = numbers.Count();
    numbers.Add(numbers[last-2]+numbers[last-1]);
    
}
int sum = 0;
foreach (var item in numbers)
{
    if (item%2==0 && item<4000000)
    {
        sum=sum+item;
    }
}
Console.WriteLine(sum);